module.exports={
products: [
    {
      _id: '1',
      name: 'korean outfit',
      category: 'Outfit',
      image: 'images/1.jpg',
      price: 180,
      brand: 'korean',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      description:'random text 5'
    },
    {
      _id: '2',
      name: 'korean Outfit',
      category: 'Outfit',
      image: 'images/2.jpg',
      price: 180,
      brand: 'korean',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      description:'random text 6'
    },
    {
      _id: '3',
      name: 'korean Outfit',
      category: 'Outfit',
      image: '/images/3.jpg',
      price: 180,
      brand: 'korean',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      description:'random text 7'
    },
    {
      _id: '4',
      name: 'korean Outfit',
      category: 'Outfit',
      image: '/images/4.jpg',
      price: 180,
      brand: 'korean',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      description:'random text 8'
    },
    {
      _id: '5',
      name: 'korean Outfit',
      category: 'Outfit',
      image: '/images/5.jpg',
      price: 180,
      brand: 'korean',
      rating: 2.5,
      numReviews: 10,
      countInStock: 6,
      description: 'randowm text 1',
    },
    {
      _id: '6',
      name: 'korean Outfit',
      category: 'Outfit',
      image: '/images/6.jpg',
      price: 180,
      brand: 'korean',
      rating: 3.5,
      numReviews: 10,
      countInStock: 6,
      escription: 'randowm text 2',
    },
    {
      _id: '7',
      name: 'korean Outfit',
      category: 'Outfit',
      image: '/images/2.jpg',
      price: 180,
      brand: 'korean',
      rating: 3.5,
      numReviews: 10,
      countInStock: 6,
      description: 'randowm text 3',
    },
    {
      _id: '8',
      name: 'korean Outfit',
      category: 'Outfit',
      image: '/images/1.jpg',
      price: 180,
      brand: 'korean',
      rating: 3.5,
      numReviews: 10,
      countInStock: 6,
      escription: 'randowm text 4',
    },
  ],
};
